// +build !ignore_autogenerated

// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/aws/aws-controllers-k8s/apis/core/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Attribute) DeepCopyInto(out *Attribute) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Attribute.
func (in *Attribute) DeepCopy() *Attribute {
	if in == nil {
		return nil
	}
	out := new(Attribute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationData) DeepCopyInto(out *AuthorizationData) {
	*out = *in
	if in.AuthorizationToken != nil {
		in, out := &in.AuthorizationToken, &out.AuthorizationToken
		*out = new(string)
		**out = **in
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.ProxyEndpoint != nil {
		in, out := &in.ProxyEndpoint, &out.ProxyEndpoint
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationData.
func (in *AuthorizationData) DeepCopy() *AuthorizationData {
	if in == nil {
		return nil
	}
	out := new(AuthorizationData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribeImagesFilter) DeepCopyInto(out *DescribeImagesFilter) {
	*out = *in
	if in.TagStatus != nil {
		in, out := &in.TagStatus, &out.TagStatus
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribeImagesFilter.
func (in *DescribeImagesFilter) DeepCopy() *DescribeImagesFilter {
	if in == nil {
		return nil
	}
	out := new(DescribeImagesFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Image) DeepCopyInto(out *Image) {
	*out = *in
	if in.ImageID != nil {
		in, out := &in.ImageID, &out.ImageID
		*out = new(ImageIdentifier)
		(*in).DeepCopyInto(*out)
	}
	if in.ImageManifest != nil {
		in, out := &in.ImageManifest, &out.ImageManifest
		*out = new(string)
		**out = **in
	}
	if in.ImageManifestMediaType != nil {
		in, out := &in.ImageManifestMediaType, &out.ImageManifestMediaType
		*out = new(string)
		**out = **in
	}
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Image.
func (in *Image) DeepCopy() *Image {
	if in == nil {
		return nil
	}
	out := new(Image)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageDetail) DeepCopyInto(out *ImageDetail) {
	*out = *in
	if in.ImageDigest != nil {
		in, out := &in.ImageDigest, &out.ImageDigest
		*out = new(string)
		**out = **in
	}
	if in.ImagePushedAt != nil {
		in, out := &in.ImagePushedAt, &out.ImagePushedAt
		*out = (*in).DeepCopy()
	}
	if in.ImageScanFindingsSummary != nil {
		in, out := &in.ImageScanFindingsSummary, &out.ImageScanFindingsSummary
		*out = new(ImageScanFindingsSummary)
		(*in).DeepCopyInto(*out)
	}
	if in.ImageScanStatus != nil {
		in, out := &in.ImageScanStatus, &out.ImageScanStatus
		*out = new(ImageScanStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ImageSizeInBytes != nil {
		in, out := &in.ImageSizeInBytes, &out.ImageSizeInBytes
		*out = new(int64)
		**out = **in
	}
	if in.ImageTags != nil {
		in, out := &in.ImageTags, &out.ImageTags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageDetail.
func (in *ImageDetail) DeepCopy() *ImageDetail {
	if in == nil {
		return nil
	}
	out := new(ImageDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageFailure) DeepCopyInto(out *ImageFailure) {
	*out = *in
	if in.FailureCode != nil {
		in, out := &in.FailureCode, &out.FailureCode
		*out = new(string)
		**out = **in
	}
	if in.FailureReason != nil {
		in, out := &in.FailureReason, &out.FailureReason
		*out = new(string)
		**out = **in
	}
	if in.ImageID != nil {
		in, out := &in.ImageID, &out.ImageID
		*out = new(ImageIdentifier)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageFailure.
func (in *ImageFailure) DeepCopy() *ImageFailure {
	if in == nil {
		return nil
	}
	out := new(ImageFailure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageIdentifier) DeepCopyInto(out *ImageIdentifier) {
	*out = *in
	if in.ImageDigest != nil {
		in, out := &in.ImageDigest, &out.ImageDigest
		*out = new(string)
		**out = **in
	}
	if in.ImageTag != nil {
		in, out := &in.ImageTag, &out.ImageTag
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageIdentifier.
func (in *ImageIdentifier) DeepCopy() *ImageIdentifier {
	if in == nil {
		return nil
	}
	out := new(ImageIdentifier)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageScanFinding) DeepCopyInto(out *ImageScanFinding) {
	*out = *in
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make([]*Attribute, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Attribute)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Severity != nil {
		in, out := &in.Severity, &out.Severity
		*out = new(string)
		**out = **in
	}
	if in.URI != nil {
		in, out := &in.URI, &out.URI
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageScanFinding.
func (in *ImageScanFinding) DeepCopy() *ImageScanFinding {
	if in == nil {
		return nil
	}
	out := new(ImageScanFinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageScanFindings) DeepCopyInto(out *ImageScanFindings) {
	*out = *in
	if in.FindingSeverityCounts != nil {
		in, out := &in.FindingSeverityCounts, &out.FindingSeverityCounts
		*out = make(map[string]*int64, len(*in))
		for key, val := range *in {
			var outVal *int64
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(int64)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Findings != nil {
		in, out := &in.Findings, &out.Findings
		*out = make([]*ImageScanFinding, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ImageScanFinding)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.ImageScanCompletedAt != nil {
		in, out := &in.ImageScanCompletedAt, &out.ImageScanCompletedAt
		*out = (*in).DeepCopy()
	}
	if in.VulnerabilitySourceUpdatedAt != nil {
		in, out := &in.VulnerabilitySourceUpdatedAt, &out.VulnerabilitySourceUpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageScanFindings.
func (in *ImageScanFindings) DeepCopy() *ImageScanFindings {
	if in == nil {
		return nil
	}
	out := new(ImageScanFindings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageScanFindingsSummary) DeepCopyInto(out *ImageScanFindingsSummary) {
	*out = *in
	if in.FindingSeverityCounts != nil {
		in, out := &in.FindingSeverityCounts, &out.FindingSeverityCounts
		*out = make(map[string]*int64, len(*in))
		for key, val := range *in {
			var outVal *int64
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(int64)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ImageScanCompletedAt != nil {
		in, out := &in.ImageScanCompletedAt, &out.ImageScanCompletedAt
		*out = (*in).DeepCopy()
	}
	if in.VulnerabilitySourceUpdatedAt != nil {
		in, out := &in.VulnerabilitySourceUpdatedAt, &out.VulnerabilitySourceUpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageScanFindingsSummary.
func (in *ImageScanFindingsSummary) DeepCopy() *ImageScanFindingsSummary {
	if in == nil {
		return nil
	}
	out := new(ImageScanFindingsSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageScanStatus) DeepCopyInto(out *ImageScanStatus) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageScanStatus.
func (in *ImageScanStatus) DeepCopy() *ImageScanStatus {
	if in == nil {
		return nil
	}
	out := new(ImageScanStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageScanningConfiguration) DeepCopyInto(out *ImageScanningConfiguration) {
	*out = *in
	if in.ScanOnPush != nil {
		in, out := &in.ScanOnPush, &out.ScanOnPush
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageScanningConfiguration.
func (in *ImageScanningConfiguration) DeepCopy() *ImageScanningConfiguration {
	if in == nil {
		return nil
	}
	out := new(ImageScanningConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Layer) DeepCopyInto(out *Layer) {
	*out = *in
	if in.LayerAvailability != nil {
		in, out := &in.LayerAvailability, &out.LayerAvailability
		*out = new(string)
		**out = **in
	}
	if in.LayerDigest != nil {
		in, out := &in.LayerDigest, &out.LayerDigest
		*out = new(string)
		**out = **in
	}
	if in.LayerSize != nil {
		in, out := &in.LayerSize, &out.LayerSize
		*out = new(int64)
		**out = **in
	}
	if in.MediaType != nil {
		in, out := &in.MediaType, &out.MediaType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Layer.
func (in *Layer) DeepCopy() *Layer {
	if in == nil {
		return nil
	}
	out := new(Layer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LayerFailure) DeepCopyInto(out *LayerFailure) {
	*out = *in
	if in.FailureCode != nil {
		in, out := &in.FailureCode, &out.FailureCode
		*out = new(string)
		**out = **in
	}
	if in.FailureReason != nil {
		in, out := &in.FailureReason, &out.FailureReason
		*out = new(string)
		**out = **in
	}
	if in.LayerDigest != nil {
		in, out := &in.LayerDigest, &out.LayerDigest
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LayerFailure.
func (in *LayerFailure) DeepCopy() *LayerFailure {
	if in == nil {
		return nil
	}
	out := new(LayerFailure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LifecyclePolicyPreviewFilter) DeepCopyInto(out *LifecyclePolicyPreviewFilter) {
	*out = *in
	if in.TagStatus != nil {
		in, out := &in.TagStatus, &out.TagStatus
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LifecyclePolicyPreviewFilter.
func (in *LifecyclePolicyPreviewFilter) DeepCopy() *LifecyclePolicyPreviewFilter {
	if in == nil {
		return nil
	}
	out := new(LifecyclePolicyPreviewFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LifecyclePolicyPreviewResult) DeepCopyInto(out *LifecyclePolicyPreviewResult) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(LifecyclePolicyRuleAction)
		(*in).DeepCopyInto(*out)
	}
	if in.AppliedRulePriority != nil {
		in, out := &in.AppliedRulePriority, &out.AppliedRulePriority
		*out = new(int64)
		**out = **in
	}
	if in.ImageDigest != nil {
		in, out := &in.ImageDigest, &out.ImageDigest
		*out = new(string)
		**out = **in
	}
	if in.ImagePushedAt != nil {
		in, out := &in.ImagePushedAt, &out.ImagePushedAt
		*out = (*in).DeepCopy()
	}
	if in.ImageTags != nil {
		in, out := &in.ImageTags, &out.ImageTags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LifecyclePolicyPreviewResult.
func (in *LifecyclePolicyPreviewResult) DeepCopy() *LifecyclePolicyPreviewResult {
	if in == nil {
		return nil
	}
	out := new(LifecyclePolicyPreviewResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LifecyclePolicyPreviewSummary) DeepCopyInto(out *LifecyclePolicyPreviewSummary) {
	*out = *in
	if in.ExpiringImageTotalCount != nil {
		in, out := &in.ExpiringImageTotalCount, &out.ExpiringImageTotalCount
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LifecyclePolicyPreviewSummary.
func (in *LifecyclePolicyPreviewSummary) DeepCopy() *LifecyclePolicyPreviewSummary {
	if in == nil {
		return nil
	}
	out := new(LifecyclePolicyPreviewSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LifecyclePolicyRuleAction) DeepCopyInto(out *LifecyclePolicyRuleAction) {
	*out = *in
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LifecyclePolicyRuleAction.
func (in *LifecyclePolicyRuleAction) DeepCopy() *LifecyclePolicyRuleAction {
	if in == nil {
		return nil
	}
	out := new(LifecyclePolicyRuleAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListImagesFilter) DeepCopyInto(out *ListImagesFilter) {
	*out = *in
	if in.TagStatus != nil {
		in, out := &in.TagStatus, &out.TagStatus
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListImagesFilter.
func (in *ListImagesFilter) DeepCopy() *ListImagesFilter {
	if in == nil {
		return nil
	}
	out := new(ListImagesFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Repository) DeepCopyInto(out *Repository) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Repository.
func (in *Repository) DeepCopy() *Repository {
	if in == nil {
		return nil
	}
	out := new(Repository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Repository) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryList) DeepCopyInto(out *RepositoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Repository, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryList.
func (in *RepositoryList) DeepCopy() *RepositoryList {
	if in == nil {
		return nil
	}
	out := new(RepositoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RepositoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositorySpec) DeepCopyInto(out *RepositorySpec) {
	*out = *in
	if in.ImageScanningConfiguration != nil {
		in, out := &in.ImageScanningConfiguration, &out.ImageScanningConfiguration
		*out = new(ImageScanningConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.ImageTagMutability != nil {
		in, out := &in.ImageTagMutability, &out.ImageTagMutability
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositorySpec.
func (in *RepositorySpec) DeepCopy() *RepositorySpec {
	if in == nil {
		return nil
	}
	out := new(RepositorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryStatus) DeepCopyInto(out *RepositoryStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryURI != nil {
		in, out := &in.RepositoryURI, &out.RepositoryURI
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryStatus.
func (in *RepositoryStatus) DeepCopy() *RepositoryStatus {
	if in == nil {
		return nil
	}
	out := new(RepositoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Repository_SDK) DeepCopyInto(out *Repository_SDK) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.ImageScanningConfiguration != nil {
		in, out := &in.ImageScanningConfiguration, &out.ImageScanningConfiguration
		*out = new(ImageScanningConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.ImageTagMutability != nil {
		in, out := &in.ImageTagMutability, &out.ImageTagMutability
		*out = new(string)
		**out = **in
	}
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryARN != nil {
		in, out := &in.RepositoryARN, &out.RepositoryARN
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
	if in.RepositoryURI != nil {
		in, out := &in.RepositoryURI, &out.RepositoryURI
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Repository_SDK.
func (in *Repository_SDK) DeepCopy() *Repository_SDK {
	if in == nil {
		return nil
	}
	out := new(Repository_SDK)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tag) DeepCopyInto(out *Tag) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tag.
func (in *Tag) DeepCopy() *Tag {
	if in == nil {
		return nil
	}
	out := new(Tag)
	in.DeepCopyInto(out)
	return out
}
